apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: bookstore
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - name: http
      port: 8086
      targetPort: http
