apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: bookstore
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: bookstore/config-server:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
              name: http
          envFrom:
            - configMapRef:
                name: bookstore-config
            - secretRef:
                name: bookstore-secrets
          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
              value: file:/config-repo
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 768Mi
